import { Given, When, Then } from "@wdio/cucumber-framework";
import { expect, browser, $ } from '@wdio/globals';
import dotenv from 'dotenv';
import { setupHealingHooks } from '../utils/healing/healingHooks';
import { SessionStore } from '../utils/sessionStore';

// Import page object instance
let generatedPage: any;
try { generatedPage = require('../page-objects/generatedPage').generatedPage; } catch (e) { console.warn('⚠️ Could not load generatedPage:', e instanceof Error ? e.message : e); }
try { if (!generatedPage) generatedPage = require('../page-objects/generatedPage').default; } catch (e) { /* ignore */ }
if (!generatedPage) {
  console.error('❌ No page objects could be loaded. Run page object generation first.');
}

dotenv.config();

setupHealingHooks();

/**
 * AUTO-GENERATED STEP DEFINITIONS
 * This file is automatically generated and deduplicated to prevent step pattern conflicts.
 * Each step pattern is unique to ensure proper Cucumber matching.
 * ✅ Self-healing enabled - will auto-regenerate on step failures
 */

/**
 * Implements: "Given the user navigates to \"https://www.automationexercise.com\""
 */
Given(/^the user navigates to "([^"]*)"$/, async function (url) {
try {
  await browser.url(url);
  try {
    await browser.waitUntil(
      async () => (await browser.execute(() => document.readyState)) === 'complete',
      { timeout: 15000, timeoutMsg: 'Page load timeout' }
    );
  } catch {
    // Page may have ads that delay readyState; continue anyway
  }
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Navigation failed: ${errorMessage}`);
}
});

/**
 * Implements: "When the user fills \"#susbscribe_email\" with \"test_1780312129002@test.com\""
 */
When(/^the user fills "([^"]*)" with "([^"]*)"$/, async function (param1, param2) {
try {
  await browser.execute(() => {
    document.querySelectorAll('iframe, ins.adsbygoogle, div[class*="ad"], div[id*="ad"], [id^="aswift_"], [id^="google_ads"]').forEach((f) => {
      f.remove();
    });
    document.body.style.overflow = '';
    document.body.style.position = '';
  });
  const el = await $(param1);
  await el.scrollIntoView();
  await el.waitForDisplayed({ timeout: 5000 });
  await el.waitForEnabled({ timeout: 5000 });
  await el.clearValue();
  await el.setValue(param2);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Fill field failed: ${errorMessage}`);
}
});

/**
 * Implements: "Then the page title should contain \"Automation Exercise\""
 */
Then(/^the page title should contain "([^"]*)"$/, async function (param1) {
try {
  const title = await browser.getTitle();
  await expect(title).toContain(param1);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Title verification failed: ${errorMessage}`);
}
});

/**
 * Implements: "Then the URL should contain \"/\""
 */
Then(/^the URL should contain "([^"]*)"$/, async function (expectedPath) {
try {
  const currentUrl = await browser.getUrl();
  await expect(currentUrl).toContain(expectedPath);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`URL verification failed: ${errorMessage}`);
}
});

/**
 * Implements: "Then the user should see \" Products\""
 */
Then(/^the user should see "([^"]*)"$/, async function (param1) {
try {
  let found = false;
  for (let i = 0; i < 10; i++) {
    found = await browser.execute((text: string) => document.body?.innerText?.toLowerCase()?.includes(text.toLowerCase()) || false, String(param1));
    if (found) break;
    await browser.pause(500);
  }
  if (!found) throw new Error(`Text not found: ${param1}`);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Text not found: ${errorMessage}`);
}
});

/**
 * Implements: "When the user clicks \"Test Cases\""
 */
When(/^the user clicks "([^"]*)"$/, async function (param1) {
try {
  await browser.execute(() => {
    document.querySelectorAll('iframe, ins.adsbygoogle, div[class*="ad"], div[id*="ad"], [id^="aswift_"], [id^="google_ads"]').forEach((f) => {
      f.remove();
    });
    document.body.style.overflow = '';
    document.body.style.position = '';
  });
  const found = await $('=' + param1);
  if (await found.isExisting()) {
    try {
      await found.scrollIntoView();
      await found.waitForClickable({ timeout: 10000 });
      await found.click();
    } catch {
      await (browser as any).execute(function(text: string) {
        document.querySelectorAll('button, a, input[type="submit"], [role="button"], .check_out, .btn').forEach((e: Element) => {
          if ((e.textContent ?? '').trim() === text) (e as HTMLElement).click();
        });
      }, param1);
    }
  } else {
    const clicked = await browser.execute((text: string) => {
      // Try finding by ID
      let el = document.querySelector('#' + CSS.escape(text));
      if (el) { (el as HTMLElement).click(); return true; }
      // Try finding clickable/text elements by text content
      const candidates = Array.from(document.querySelectorAll('a, button, [role="button"], label, span, input[type="radio"], input[type="checkbox"], input[type="submit"], input[type="button"], div, p, li, td, th'));
      for (const e of candidates) {
        const t = (e.textContent || '').trim().toLowerCase();
        if (t === text.toLowerCase()) {
          if (e.tagName === 'LABEL') { (e as HTMLElement).click(); return true; }
          if (e.tagName === 'INPUT' && (e as HTMLInputElement).type === 'radio' || (e as HTMLInputElement).type === 'checkbox') { (e as HTMLElement).click(); return true; }
          (e as HTMLElement).click(); return true;
        }
      }
      // Try partial text match
      for (const e of candidates) {
        const t = (e.textContent || '').trim().toLowerCase();
        if (t.startsWith(text.toLowerCase()) || text.toLowerCase().startsWith(t)) {
          if (e.tagName === 'LABEL') { (e as HTMLElement).click(); return true; }
          (e as HTMLElement).click(); return true;
        }
      }
      return false;
    }, String(param1));
    if (!clicked) throw new Error(`Could not find element with text: ${param1}`);
  }
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Click failed: ${errorMessage}`);
}
});

/**
 * Selects an option from a <select> dropdown by its option value
 */
When(/^the user selects "([^"]*)" from "([^"]*)"$/, async function (optionValue, selectId) {
try {
  const sel = selectId.startsWith('#') ? selectId : `#${selectId}`;
  await (browser as any).execute(function(sel: string, val: string) {
    const el = document.querySelector(sel) as HTMLSelectElement;
    if (el) { el.value = val; el.dispatchEvent(new Event('change', { bubbles: true })); return true; }
    return false;
  }, sel, optionValue);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Select failed: ${errorMessage}`);
}
});

/**
 * Checks or unchecks a checkbox by selector
 */
When(/^the user (checks|unchecks) "([^"]*)"$/, async function (action, selector) {
try {
  await (browser as any).execute(function(sel: string, checked: boolean) {
    const el = document.querySelector(sel) as HTMLInputElement;
    if (el) { el.checked = checked; el.dispatchEvent(new Event('change', { bubbles: true })); return true; }
    return false;
  }, selector, action === 'checks');
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Checkbox action failed: ${errorMessage}`);
}
});

/**
 * Clicks an element by CSS selector (supports attribute selectors like [data-qa='value'])
 * Hides ad iframes/overlays before clicking to avoid "element not clickable" errors.
 */
When(/^the user clicks element "([^"]*)"$/, async function (selector) {
try {
  await browser.execute(() => {
    document.querySelectorAll('iframe, ins.adsbygoogle, div[class*="ad"], div[id*="ad"], [id^="aswift_"], [id^="google_ads"]').forEach((f) => {
      f.remove();
    });
    document.body.style.overflow = '';
    document.body.style.position = '';
  });
  const el = await $(selector);
  try {
    await el.waitForClickable({ timeout: 10000 });
    await el.click();
  } catch {
    await (browser as any).execute(function(sel: string) {
      (document.querySelector(sel) as HTMLElement)?.click();
    }, selector);
  }
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Element click failed: ${errorMessage}`);
}
});