import { Given, When, Then } from "@wdio/cucumber-framework";
import { expect, browser, $ } from '@wdio/globals';
import dotenv from 'dotenv';
import { setupHealingHooks } from '../utils/healing/healingHooks';
import { SessionStore } from '../utils/sessionStore';

// Import page object instance
let generatedPage: any;
try { generatedPage = require('../page-objects/generatedPage').generatedPage; } catch (e) { console.warn('⚠️ Could not load generatedPage:', e instanceof Error ? e.message : e); }
try { if (!generatedPage) generatedPage = require('../page-objects/generatedPage').default; } catch (e) { /* ignore */ }
if (!generatedPage) {
  console.error('❌ No page objects could be loaded. Run page object generation first.');
}

dotenv.config();

setupHealingHooks();

/**
 * AUTO-GENERATED STEP DEFINITIONS
 * This file is automatically generated and deduplicated to prevent step pattern conflicts.
 * Each step pattern is unique to ensure proper Cucumber matching.
 * ✅ Self-healing enabled - will auto-regenerate on step failures
 */

/**
 * Implements: "Given the user navigates to \"https://www.e-business.sro.vic.gov.au/calculators/livestock-duty\""
 */
Given(/^the user navigates to "([^"]*)"$/, async function (url) {
try {
  await browser.url(url);
  await browser.waitUntil(
    async () => (await browser.execute(() => document.readyState)) === 'complete',
    { timeout: 10000, timeoutMsg: 'Page did not load' }
  );
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Navigation failed: ${errorMessage}`);
}
});

/**
 * Implements: "When the user submits the form"
 */
When(/^the user submits the form$/, async function () {
try {
  await browser.execute(() => document.querySelectorAll('iframe').forEach((f) => ((f as HTMLElement).style.display = 'none')));
  await $('[type="submit"], button[type="submit"], button:not([type])').click();
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Form submit failed: ${errorMessage}`);
}
});

/**
 * Implements: "Then the page title should contain \"Livestock duty calculator | State Revenue Office\""
 */
Then(/^the page title should contain "([^"]*)"$/, async function (param1) {
try {
  const title = await browser.getTitle();
  await expect(title).toContain(param1);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Title verification failed: ${errorMessage}`);
}
});

/**
 * Implements: "Then the URL should contain \"/calculators/livestock-duty\""
 */
Then(/^the URL should contain "([^"]*)"$/, async function (expectedPath) {
try {
  const currentUrl = await browser.getUrl();
  await expect(currentUrl).toContain(expectedPath);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`URL verification failed: ${errorMessage}`);
}
});

/**
 * Implements: "Then the user should see \"livestock duty\""
 */
Then(/^the user should see "([^"]*)"$/, async function (param1) {
try {
  const found = await browser.execute((text: string) => document.body?.innerText?.includes(text) || false, String(param1));
  if (!found) throw new Error(`Text not found: ${param1}`);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Text not found: ${errorMessage}`);
}
});

/**
 * Implements: "When the user clicks \"livestockTypeCattle\""
 */
When(/^the user clicks "([^"]*)"$/, async function (param1) {
try {
  const found = await $('=' + param1);
  if (await found.isExisting()) {
    await found.click();
  } else {
    const clicked = await browser.execute((text: string) => {
      // Try finding by ID
      let el = document.querySelector('#' + CSS.escape(text));
      if (el) { (el as HTMLElement).click(); return true; }
      // Try finding clickable/text elements by text content
      const candidates = Array.from(document.querySelectorAll('a, button, [role="button"], label, span, input[type="radio"], input[type="checkbox"], input[type="submit"], input[type="button"], div, p, li, td, th'));
      for (const e of candidates) {
        const t = (e.textContent || '').trim().toLowerCase();
        if (t === text.toLowerCase()) {
          if (e.tagName === 'LABEL') { (e as HTMLElement).click(); return true; }
          if (e.tagName === 'INPUT' && (e as HTMLInputElement).type === 'radio' || (e as HTMLInputElement).type === 'checkbox') { (e as HTMLElement).click(); return true; }
          (e as HTMLElement).click(); return true;
        }
      }
      // Try partial text match
      for (const e of candidates) {
        const t = (e.textContent || '').trim().toLowerCase();
        if (t.startsWith(text.toLowerCase()) || text.toLowerCase().startsWith(t)) {
          if (e.tagName === 'LABEL') { (e as HTMLElement).click(); return true; }
          (e as HTMLElement).click(); return true;
        }
      }
      return false;
    }, String(param1));
    if (!clicked) throw new Error(`Could not find element with text: ${param1}`);
  }
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Click failed: ${errorMessage}`);
}
});

/**
 * Implements: "When the user fills \"#primaryPigsValue\" with \"500000\""
 */
When(/^the user fills "([^"]*)" with "([^"]*)"$/, async function (param1, param2) {
try {
  await browser.execute(() => document.querySelectorAll('iframe').forEach((f) => ((f as HTMLElement).style.display = 'none')));
  const el = await $(param1);
  await el.waitForEnabled({ timeout: 5000 });
  await el.clearValue();
  await el.setValue(param2);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  throw new Error(`Fill field failed: ${errorMessage}`);
}
});