export const TIMEOUTS = {
  DEFAULT_TEST_TIMEOUT: 60000,
  PAGE_LOAD_TIMEOUT: 15000,
  API_TIMEOUT: 120000,
  API_RETRY_DELAY: 1000,
  HEALTH_CHECK_TIMEOUT: 5000,
  BROWSER_PAUSE: 1000,
};

export const RETRY_CONFIG = {
  MAX_RETRIES: 3,
  INITIAL_DELAY_MS: 1000,
  BACKOFF_MULTIPLIER: 2,
};

export const DOM_CONFIG = {
  MAX_DOM_LENGTH: 5000,
  TRUNCATION_MESSAGE: '\n<!-- ...truncated... -->',
};

export const OLLAMA_CONFIG = {
  DEFAULT_BASE_URL: 'http://localhost:11434',
  DEFAULT_MODEL: 'llama3',
  DEFAULT_TEMPERATURE: 0.3,
  DEFAULT_MAX_TOKENS: 500,
  DEFAULT_TOP_P: 0.9,
  DEFAULT_REPEAT_PENALTY: 1.1,
};

export const AI_GENERATION_CONFIG = {
  STEP_TEMPERATURE: 0.2,
  STEP_MAX_TOKENS: 500,
  PROMPT_TEMPERATURE: 0.4,
  PROMPT_MAX_TOKENS: 800,
  STEPS_RETRIES: 3,
  STEPS_RETRY_DELAY: 2000,
};

export const ERROR_CODES = {
  INVALID_URL: 'INVALID_URL',
  NETWORK_ERROR: 'NETWORK_ERROR',
  API_ERROR: 'API_ERROR',
  GENERATION_FAILED: 'GENERATION_FAILED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  SERVER_ERROR_START: 500,
  SERVER_ERROR_END: 600,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  TOO_MANY_REQUESTS: 429,
  REQUEST_TIMEOUT: 408,
};
